image:
  file: .gitpod.Dockerfile
tasks:
  - name: Prepare Build
    init: ./build.sh

vscode:
  extensions:
    - ms-vscode.cpptools
    - github.copilot
    - ms-vscode.cpptools-extension-pack
    - Guyutongxue.cpp-reference
    - visualstudioexptteam.vscodeintellicode
    - timonwong.shellcheck